// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4909.Bionics2016.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc4909.Bionics2016.Robot;

/**
 *
 */
public class StartShooter extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	
	private double targetRPM = 0;
	private double startTime;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public StartShooter(double tRPM) {
    	
    	this.targetRPM = tRPM;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	startTime = Timer.getFPGATimestamp();
    	//Robot.shooter.setShooterWheels(1.0);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//targetRPM=((-Robot.oi.operatorControl.getRawAxis(3)+1)*2500);
    	//Robot.shooter.useLeftRate(targetRPM);
    	//Robot.shooter.useRightRate(targetRPM);
    	//Robot.shooter.setShooterRPM(targetRPM);
        //SmartDashboard.putNumber("Target RPM", targetRPM);
        //SmartDashboard.putNumber("left encoder", Robot.shooter.getLeftRPM());
        //SmartDashboard.putNumber("right encoder", Robot.shooter.getRightRPM());
        Robot.shooter.setShooterWheels(targetRPM / 4000);
       // System.out.println(Robot.shooter.getRightRPM());
     //   System.out.println(Robot.shooter.getLeftRPM());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Timer.getFPGATimestamp() - startTime > targetRPM / 1000;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
